### ISSUE TITLE
Go application tutorial does not work in 0.35.0

### ISSUE THREAD

**Issue by ppedziwiatr** [tendermint/tendermint#7329]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.35.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://docs.tendermint.com/v0.35/tutorials/go.html

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Big Sur 11.6, M1
- **Install tools**:
- **Others**: go1.17.3 darwin/amd64 

**What happened**:
Tutorial from https://docs.tendermint.com/v0.35/tutorials/go.html does not work on tendermint 0.35.0

1. https://docs.tendermint.com/v0.35/tutorials/go.html#_1-5-getting-up-and-running
`go get github.com/tendermint/tendermint@master` is currently causing the dev version of the 0.36 to be installed. This in turn is causing lot of issues in the `main.go` 
```
./main.go:35:38: not enough arguments in call to server.NewSocketServer
	have (string, *KVStoreApplication)
	want ("github.com/tendermint/tendermint/libs/log".Logger, string, "github.com/tendermint/tendermint/abci/types".Application)
./main.go:36:8: server.SetLogger undefined (type service.Service has no field or method SetLogger)
./main.go:37:24: not enough arguments in call to server.Start
	have ()
	want (context.Context)
./main.go:41:14: server.Stop undefined (type service.Service has no field or method Stop)
```

This can be fixed by using 
`go get github.com/tendermint/tendermint@97a3e44e0724f2017079ce24d36433f03124c09e` - which in turn installs the v0.35

2. After fixing issue from previous point, there are still two errors: 
```
./main.go:33:12: undefined: "github.com/tendermint/tendermint/libs/log".NewTMLogger
./main.go:33:28: undefined: "github.com/tendermint/tendermint/libs/log".NewSyncWriter
```
I believe this is caused by the changes introduced in https://github.com/tendermint/tendermint/commit/3635c7a3829d309c33b998044384b6fdcb8e8a2c#diff-c9a52835336f0882d50020372fed45f09e384267174bcee43dcfaa47dfefb54a - the tutorial hasn't been updated after merging this change. 

**What you expected to happen**:
The example Go app compiles and runs properly

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
Follow the instructions from https://docs.tendermint.com/v0.35/tutorials/go.html

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by ppedziwiatr** [comment]
Changing 
```go
// logger := log.NewTMLogger(log.NewSyncWriter(os.Stdout))
 logger := log.MustNewDefaultLogger(log.LogFormatPlain, log.LogLevelInfo, false)
 ```
 seems to fix the issue, I've prepared a PR.

**Comment by creachadair** [comment]
Closed in #7331, thank for the report and the quick fix.
