### ISSUE TITLE
go 1.8 failing to build against http in golang.org/x/net/http2/go18 on OS X

### ISSUE THREAD

**Issue by joeblew99** [tendermint/tendermint#417]
i pulled the latest, go get -u github.com/tendermint/tendermint/cmd/tendermint 

But seems its broken on go 1.8.

````


x-MacBook-Pro:tendermint apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build325127552=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"


x-MacBook-Pro:tendermint apple$ pwd
/Users/apple/workspace/go/src/github.com/tendermint/tendermint/cmd/tendermint

x-MacBook-Pro:tendermint apple$ go build
# golang.org/x/net/http2
../../../../../golang.org/x/net/http2/go18.go:15: c.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
../../../../../golang.org/x/net/http2/go18.go:17: undefined: http.Pusher
../../../../../golang.org/x/net/http2/go18.go:20: undefined: http.PushOptions
../../../../../golang.org/x/net/http2/go18.go:31: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
../../../../../golang.org/x/net/http2/go18.go:32: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
../../../../../golang.org/x/net/http2/go18.go:41: undefined: http.ErrAbortHandler
../../../../../golang.org/x/net/http2/go18.go:45: req.GetBody undefined (type *http.Request has no field or method GetBody)
../../../../../golang.org/x/net/http2/go18.go:49: undefined: http.NoBody
# google.golang.org/grpc/credentials
../../../../../google.golang.org/grpc/credentials/credentials_util_go18.go:52: cfg.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
x-MacBook-Pro:tendermint apple$ clear

````

**Comment by joeblew99** [comment]
i read that http2 is included in go 1.8, so i am guessing using the golang.org/x/net/http2 package is not correct.

I am assuming that the golang team backported the fixes into the X repo, hence the go1.8.go tag, to support code bases that are not on golang 1.8 yet.

what version of golang do the tendermint team support ?

**Comment by joeblew99** [comment]
Using glide also fails.
You can see its using the vendored code at "# github.com/tendermint/tendermint/vendor/golang.org/x/net/http2"
Gets the same error as when not using glide.


````

x-MacBook-Pro:tendermint apple$ go get github.com/Masterminds/glide
x-MacBook-Pro:tendermint apple$ cd $GOPATH/src/github.com/tendermint/tendermint
x-MacBook-Pro:tendermint apple$ glide install
[INFO]	Downloading dependencies. Please wait...

x-MacBook-Pro:tendermint apple$ go install ./cmd/tendermint
# github.com/tendermint/tendermint/vendor/golang.org/x/net/http2
vendor/golang.org/x/net/http2/go18.go:15: c.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
vendor/golang.org/x/net/http2/go18.go:17: undefined: http.Pusher
vendor/golang.org/x/net/http2/go18.go:20: undefined: http.PushOptions
vendor/golang.org/x/net/http2/go18.go:31: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/golang.org/x/net/http2/go18.go:32: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/golang.org/x/net/http2/go18.go:41: undefined: http.ErrAbortHandler
vendor/golang.org/x/net/http2/go18.go:45: req.GetBody undefined (type *http.Request has no field or method GetBody)
vendor/golang.org/x/net/http2/go18.go:49: undefined: http.NoBody

````

**Comment by joeblew99** [comment]
what is the current supported golang version ?

**Comment by melekes** [comment]
Thanks for reporting this! It should work fine with Golang `1.7.4`

**Comment by joeblew99** [comment]
ok thanks @melekes 

bummer. I need 1.8 for some other code bases.

nor sure what to do now.

**Comment by ethanfrey** [comment]
If you want to take a stab at porting it to 1.8 while also supporting 1.7, you can make a PR and we'll review quickly.  If it is only the http2 support (not that much changed between 1.7 and 1.8) then it should not be that difficult...

Or you can wait until this is higher priority here. But probably a few weeks at least.

**Comment by ethanfrey** [comment]
@joeblew99 I took a bit of a look in this and it seems quite odd.

The x/net/http2 lib has explicit go18 support (as your file mentions) and the version in glide seems to mirror master.

 One of the compile failures: 
`vendor/golang.org/x/net/http2/go18.go:17: undefined: http.Pusher`
https://github.com/golang/net/blob/master/http2/go18.go#L17

Seems to contradict 1.8 standard lib: https://godoc.org/net/http#Pusher

And I found no such issue on the github issue tracker: https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20http2%201.8

Odd... 

Do you also have 1.7 standard libs on your computer?  Can you try in a fresh environment that only had 1.8 installed?  Or double (triple) check your GOPATH, GOBIN, GOROOT settings...

**Comment by melekes** [comment]
@joeblew99 If updated dependencies break builds, install the vendored commits using `glide`:

```
cd $GOPATH/github.com/tendermint/tendermint
make get_vendor_deps
go build ./cmd/tendermint
```

I can confirm that TM builds successfully with Golang 1.8 using vendored dependencies.

**Comment by melekes** [comment]
Plus, I would like to remind you can always drop in the binary https://tendermint.com/intro/download-tendermint instead of building TM from source.

**Comment by gedw99** [comment]
@melekes Thanks for the heads up on slack.

i cant believe, but no dice for me.
i deleted $GOPATH/src/github.com/tendermint
I even deleted the all golang.com src and pkg.

then i tried this way:
````
go get -u github.com/tendermint/tendermint
cd $GOPATH/src/github.com/tendermint/tendermint
make get_vendor_deps
go build ./cmd/tendermint
# github.com/tendermint/tendermint/vendor/golang.org/x/net/http2
vendor/golang.org/x/net/http2/go18.go:15: c.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
vendor/golang.org/x/net/http2/go18.go:17: undefined: http.Pusher
vendor/golang.org/x/net/http2/go18.go:20: undefined: http.PushOptions
vendor/golang.org/x/net/http2/go18.go:31: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/golang.org/x/net/http2/go18.go:32: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/golang.org/x/net/http2/go18.go:41: undefined: http.ErrAbortHandler
vendor/golang.org/x/net/http2/go18.go:45: req.GetBody undefined (type *http.Request has no field or method GetBody)
vendor/golang.org/x/net/http2/go18.go:49: undefined: http.NoBody
````
Got exact same error about http.


Then i tried deleting all of tendermint again, went for the and the git clone technique:
````
cd $GOPATH/src/github.com
mkdir tendermint
cd tendermint
git clone https://github.com/tendermint/tendermint.git
cd $GOPATH/src/github.com/tendermint/tendermint
make get_vendor_deps
go build ./cmd/tendermint
# github.com/tendermint/tendermint/vendor/golang.org/x/net/http2
vendor/golang.org/x/net/http2/go18.go:15: c.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
vendor/golang.org/x/net/http2/go18.go:17: undefined: http.Pusher
vendor/golang.org/x/net/http2/go18.go:20: undefined: http.PushOptions
vendor/golang.org/x/net/http2/go18.go:31: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/golang.org/x/net/http2/go18.go:32: h1.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/golang.org/x/net/http2/go18.go:41: undefined: http.ErrAbortHandler
vendor/golang.org/x/net/http2/go18.go:45: req.GetBody undefined (type *http.Request has no field or method GetBody)
vendor/golang.org/x/net/http2/go18.go:49: undefined: http.NoBody

````

Got exact same error about http.

Something very weird.
Am not having these types of issues on other projects, but who knows.
I might try to do a build inside docker, just to isolate things.

**Comment by gedw99** [comment]
Wondering if its something with the golang env setup on my OSX ?

Here is mine. Maybe you can send me yours.
````
x-MacBook-Pro:tendermint apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build206091360=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

````

**Comment by melekes** [comment]
> Wondering if its something with the golang env setup on my OSX ?

I was building on Ubuntu 14.04. So, yes, I think this could be the reason. Very weird.

**Comment by ebuchman** [comment]
Hmm I just upgraded to 1.8 and it installed on a fresh GOPATH with no problem. I'm using `brew` for the install:

```
captaincandy:tendermint$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/captaincandy/newgo18"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d1/jtvbghl57clbfd4jtz1zcpkh0000gn/T/go-build589927775=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by joeblew99** [comment]
Fixed.

i had a homebrew and a non homebrew golang installed. 
Sorry about this :)

**Comment by Davidrjx** [comment]
my go version is 1.7.4 amd64. i came with similar problem about http "tlsConfig.Clone undefined" . can you have any solution? is this version compatible case?

**Comment by melekes** [comment]
@Davidrjx we don't support Go versions older than 1.9. Please upgrade to 1.9
